name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.7.3
      options: --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Install dependencies
      run: pip install -U online-judge-verify-helper

    - name: Run verify
      run: |
        cd verify/
        oj-verify run --jobs 4