name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.7.3
      options: --security-opt seccomp=unconfined

    steps:
    - name: Install latest git
      run: |
        apt-get update
        apt-get install software-properties-common -y
        apt-add-repository ppa:git-core/ppa -y
        apt-get install git -y

    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get install python3 libpython3.8 python3-dev python3-pip bash libxml2-dev libxslt-dev build-essential binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake curl wget time -y

    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -U online-judge-verify-helper

    - name: Run verify
      run: |
        cd verify/
        oj-verify run --jobs 4
