name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.7.3
      options: --security-opt seccomp=unconfined

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U online-judge-verify-helper

    - name: Run verify
      run: |
        cd verify/
        oj-verify run --jobs 4