name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.7.3
      options: --security-opt seccomp=unconfined

    steps:
    - name: Install latest git
      run: |
        apt-get update
        apt-get install software-properties-common -y
        apt-add-repository ppa:git-core/ppa -y
        apt-get install git -y
        git config --global --add safe.directory /__w/compe-library.cr/compe-library.cr

    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
      env:
        ImageOS: ubuntu18

    - name: Install dependencies
      run: |
        apt-get install python3 libpython3.8 python3-dev python3-pip bash libxml2-dev libxslt-dev build-essential binutils-dev libcurl4-openssl-dev zlib1g-dev libdw-dev libiberty-dev cmake curl wget time -y

    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -U online-judge-verify-helper
        python3 -m pip install beautifulsoup4

    - name: Install crystal dependencies
      run: |
        shards install

    - name: Run verify and generate docs
      run: |
        rm -rf lib/*/lib
        rm -rf lib/atcoder/verify/*
        oj-verify run --jobs 4
        crystal docs --progress --stats --time -o dist/api
        rm -rf lib/
        rm -rf bin/ameba.cr
        oj-verify docs --jobs 4
        python3 ./scripts/insert-mathjax.py

    - name: Build bundled docs
      run: |
        echo "gem 'jekyll-theme-windows95'" >> .verify-helper/markdown/Gemfile
        gem install bundler
        bundle install --gemfile=.verify-helper/markdown/Gemfile --path .vendor/bundle
        bundle exec --gemfile=.verify-helper/markdown/Gemfile jekyll build --source .verify-helper/markdown --destination dist/docs --baseurl compe-library.cr/docs

    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist

  lint:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:1.7.3
      options: --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Install Crystal dependencies
        run: |
          shards install --ignore-crystal-version
      - name: Run linter
        run: ./bin/ameba
